services:
  - type: web
    name: todo-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/todo-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080 